# Generated by Django 5.2 on 2025-04-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_pricehistory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='date',
            field=models.DateField(),
        ),
    ]
