# Generated by Django 5.2 on 2025-05-06 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_pricehistory_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=25, unique=True)),
                ('buyer', models.PositiveIntegerField()),
                ('seller', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.companyprofile')),
            ],
            options={
                'verbose_name': 'Floor Sheet Entry',
                'verbose_name_plural': 'Floor Sheet Entries',
                'ordering': ['-date'],
            },
        ),
    ]
