# Generated by Django 5.2 on 2025-05-11 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_floorsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='companynews',
            name='news_url',
            field=models.URLField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companynews',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.companyprofile'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='news_date',
            field=models.DateTimeField(),
        ),
    ]
